export const POPULATE_CUSTOMERS = 'POPULATE_CUSTOMERS';
export const UPDATE_CUSTOMERS_LOADER = 'UPDATE_CUSTOMERS_LOADER';
export const UPDATE_SELECTED_CUSTOMER = 'UPDATE_SELECTED_CUSTOMER';
export const UPDATE_CUSTOMER_PAGINATION = 'UPDATE_CUSTOMER_PAGINATION';
export const UPDATE_CUSTOMER_PAGINATION_LINKS =
  'UPDATE_CUSTOMER_PAGINATION_LINKS';
export const TOGGLE_CUSTOMER_TYPE = 'TOGGLE_CUSTOMER_TYPE';
