export const UPDATE_APPROVAL_LOADER = 'UPDATE_APPROVAL_LOADER';
export const POPULATE_APPROVALS = 'POPULATE_APPROVALS';
export const POPULATE_APPROVERS = 'POPULATE_APPROVERS';
export const UPDATE_APPROVAL_PAGINATION = 'UPDATE_APPROVAL_PAGINATION';
export const UPDATE_APPROVAL_PAGINATION_LINKS =
  'UPDATE_APPROVAL_PAGINATION_LINKS';
export const UPDATE_SELECTED_APPROVAL = 'UPDATE_SELECTED_APPROVAL';
export const UPDATE_APPROVAL_MODAL = 'UPDATE_APPROVAL_MODAL';
export const MANAGE_APPROVALS = 'MANAGE_APPROVALS';
export const UPDATE_APPROVAL_TICKET_FORM = 'UPDATE_APPROVAL_TICKET_FORM';
