export const UPDATE_ASSESS_LOADER = 'UPDATE_ASSESS_LOADER';
export const POPULATE_ASSESSORS = 'POPULATE_ASSESSORS';
export const POPULATE_ASSESSMENTS = 'POPULATE_ASSESSMENTS';
export const UPDATE_ASSESSMENT_PAGINATION = 'UPDATE_ASSESSMENT_PAGINATION';
export const UPDATE_ASSESSMENT_PAGINATION_LINKS =
  'UPDATE_ASSESSMENT_PAGINATION_LINKS';
export const UPDATE_SELECTED_ASSESSMENT = 'UPDATE_SELECTED_ASSESSMENT';
export const UPDATE_ASSESSMENT_MODAL = 'UPDATE_ASSESSMENT_MODAL';
export const MANAGE_ASSESSMENTS = 'MANAGE_ASSESSMENTS';
