version: '2.3'

services:
  web: &default
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      HOST: 0.0.0.0
  # ci:
  #   <<: *default
  #   build:
  #     context: .
  #     target: release
  #   ports:
  #     - '3031:3031'
  #   volumes: []
volumes:
  node_modules:
    driver: local
