export const UPDATE_FINANCE_LOADER = 'UPDATE_FINANCE_LOADER';
export const POPULATE_FINANCES = 'POPULATE_FINANCES';
export const POPULATE_FINANCIERS = 'POPULATE_FINANCIERS';
export const UPDATE_FINANCE_PAGINATION = 'UPDATE_FINANCE_PAGINATION';
export const UPDATE_FINANCE_PAGINATION_LINKS =
  'UPDATE_FINANCE_PAGINATION_LINKS';
export const UPDATE_SELECTED_FINANCE = 'UPDATE_SELECTED_FINANCE';
export const UPDATE_FINANCE_MODAL = 'UPDATE_FINANCE_MODAL';
export const MANAGE_FINANCES = 'MANAGE_FINANCES';
export const UPDATE_FINANCE_TICKET_FORM = 'UPDATE_FINANCE_TICKET_FORM';
