export const FETCHING = 'FETCHING';
export const FETCH_COMPLETE = 'FETCH_COMPLETE';
export const GENERAL_ERROR = 'GENERAL_ERROR';

// SHARED module action constants(types)
export const UPDATE_DOCUMENT_TITLE = 'UPDATE_DOCUMENT_TITLE';
export const UPDATE_DOCUMENT_ROUTE = 'UPDATE_DOCUMENT_ROUTE';
export const POPULATE_IDENTITY_TYPES = 'POPULATE_IDENTITY_TYPES';
export const UPDATE_SHARED_LOADER = 'UPDATE_SHARED_LOADER';
export const TOGGLE_SIDEBAR_MENU = 'TOGGLE_SIDEBAR_MENU';
