export const POPULATE_CLAIMS = 'POPULATE_CLAIMS';
export const UPDATE_SELECTED_CLAIM = 'UPDATE_SELECTED_CLAIM';
export const MANAGE_CLAIMS = 'MANAGE_CLAIMS';
export const UPDATE_CLAIMS_LOADER = 'UPDATE_CLAIMS_LOADER';
export const UPDATE_ACCIDENT_DETAILS_FORM = 'UPDATE_ACCIDENT_DETAILS_FORM';
export const UPDATE_DRIVER_DETAILS_FORM = 'UPDATE_DRIVER_DETAILS_FORM';
export const UPDATE_DRIVER_DETAILS_FORM_ERRORS =
  'UPDATE_DRIVER_DETAILS_FORM_ERRORS';
export const UPDATE_POLICE_DETAILS_FORM = 'UPDATE_POLICE_DETAILS_FORM';
export const MANAGE_OTHER_PARTIES = 'MANAGE_OTHER_PARTIES';
export const MANAGE_PASSENGERS = 'MANAGE_PASSENGERS';
export const MANAGE_INJURED_PEOPLE = 'MANAGE_INJURED_PEOPLE';
export const MANAGE_WITNESS = 'MANAGE_WITNESS';
export const UPDATE_CLAIM_PAGINATION = 'UPDATE_CLAIM_PAGINATION';
export const UPDATE_CLAIM_PAGINATION_LINKS = 'UPDATE_CLAIM_PAGINATION_LINKS';
export const MANAGE_VEHICLE_DAMAGE_DETAILS = 'MANAGE_VEHICLE_DAMAGE_DETAILS';
export const UPDATE_CLAIMANT_STATEMENT = 'UPDATE_CLAIMANT_STATEMENT';
export const POPULATE_VEHICLE_DAMAGE_DETAILS =
  'POPULATE_VEHICLE_DAMAGE_DETAILS';
export const POPULATE_INJURED_PEOPLE = 'POPULATE_INJURED_PEOPLE';
export const POPULATE_OTHER_PARTIES = 'POPULATE_OTHER_PARTIES';
export const POPULATE_PASSENGERS = 'POPULATE_PASSENGERS';
export const POPULATE_WITNESS = 'POPULATE_WITNESS';
