export const UPDATE_AUTH_LOADER = 'UPDATE_AUTH_LOADER';
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';
export const UPDATE_LOGIN_FORM_ERRORS = 'UPDATE_LOGIN_FORM_ERRORS';
export const AUTHENTICATE = 'AUTHENTICATE';
export const IN_AUTHENTICATE = 'IN_AUTHENTICATE';
